function fp_export_web(varargin)
% FP_EXPORT_WEB
% Builds a small, committable docs/ bundle for GitHub Pages.
%
% The raw run folders are far too large for git — a single run's animations
% run to hundreds of megabytes. This copies the stills as-is, shrinks a
% curated subset of animations to web size, rewrites the asset paths, and
% writes everything into docs/ so that folder can be committed while
% Pendulum_Control_Run_*/ stays ignored.
%
% PREREQUISITE
%   Run fp_build_report first — this reads the report_data.js it produces.
%
% USAGE
%   fp_export_web                       % latest run, default settings
%   fp_export_web('Pendulum_Control_Run_003')
%   fp_export_web(..., 'gifs', {'LQR','FuzzyPID_Sugeno'})
%   fp_export_web(..., 'max_mb', 8)
%
% OPTIONS
%   'run'        run folder to publish (default: the last one in the bundle)
%   'gifs'       controllers whose animations to include
%                (default: LQR + the best fuzzy controller)
%   'gif_width'  pixel width of web GIFs           (default 480)
%   'gif_frames' frames kept per web GIF           (default 60)
%   'disturb'    disturbance types to include      (default {'kick'})
%   'max_mb'     warn if the bundle exceeds this   (default 25)
%
% OUTPUT
%   docs/
%     index.html          copy of report.html
%     report_data.js      paths rewritten to assets/
%     assets/figures/...  PNGs, copied as-is
%     assets/anim/...     shrunk GIFs

o = parse_opts(varargin);

fprintf('\n[fp_export_web] Building docs/ bundle\n');

% ---- Load the data bundle ----------------------------------------------
if ~isfile('report_data.js')
    error('report_data.js not found. Run fp_build_report first.');
end
raw = fileread('report_data.js');
i1  = find(raw=='{',1);  i2 = find(raw=='}',1,'last');
data = jsondecode(raw(i1:i2));

runs = data.runs;
if ~iscell(runs), runs = num2cell(runs); end

% ---- Pick the run to publish -------------------------------------------
idx = numel(runs);
if ~isempty(o.run)
    idx = [];
    for i = 1:numel(runs)
        if strcmp(runs{i}.name, o.run), idx = i; break; end
    end
    if isempty(idx), error('Run "%s" not in report_data.js', o.run); end
end
run = runs{idx};
fprintf('  Publishing: %s\n', run.name);

% ---- Decide which controllers get animations ---------------------------
ctrls = run.controllers;
if ~iscell(ctrls), ctrls = num2cell(ctrls); end
gif_keys = o.gifs;
if isempty(gif_keys)
    gif_keys = auto_pick_gifs(ctrls);
end
fprintf('  Animations for: %s\n', strjoin(gif_keys, ', '));

% ---- Prepare folders ----------------------------------------------------
docs = 'docs';
a_fig = fullfile(docs,'assets','figures');
a_ani = fullfile(docs,'assets','anim');
for d = {docs, fullfile(docs,'assets'), a_fig, a_ani}
    if ~exist(d{1},'dir'), mkdir(d{1}); end
end

n_png = 0; n_gif = 0;

% ---- Baseline controllers ----------------------------------------------
for i = 1:numel(ctrls)
    c = ctrls{i};
    [ctrls{i}, np, ng] = process_ctrl(c, '', gif_keys, a_fig, a_ani, o);
    n_png = n_png + np;  n_gif = n_gif + ng;
end
run.controllers = ctrls;

% ---- Shared run figures -------------------------------------------------
shared = {'params_png','mf_png','surface_png','heatmap_png', ...
          'comparison_png','metrics_png'};
for i = 1:numel(shared)
    f = shared{i};
    if isfield(run,f) && ~isempty(run.(f))
        run.(f) = copy_png(run.(f), a_fig);
        n_png = n_png + 1;
    end
end

% ---- Disturbances -------------------------------------------------------
if isfield(run,'disturbances') && ~isempty(run.disturbances)
    ds = run.disturbances;
    if ~iscell(ds), ds = num2cell(ds); end
    for di = 1:numel(ds)
        d = ds{di};
        keep_media = any(strcmpi(d.type, o.disturb));
        dc = d.controllers;
        if ~iscell(dc), dc = num2cell(dc); end
        for ci = 1:numel(dc)
            if keep_media
                [dc{ci}, np, ng] = process_ctrl(dc{ci}, [d.type '_'], ...
                                                gif_keys, a_fig, a_ani, o);
                n_png = n_png + np;  n_gif = n_gif + ng;
            else
                dc{ci} = blank_assets(dc{ci});
            end
        end
        d.controllers = dc;
        ds{di} = d;
    end
    run.disturbances = ds;
end

% ---- Write the bundle ---------------------------------------------------
data.runs = {run};                       % publish one run only
data.web_build = struct('source_run',run.name, ...
                        'gif_controllers',{gif_keys}, ...
                        'disturbance_media',{o.disturb}, ...
                        'built',char(datetime('now','Format','yyyy-MM-dd HH:mm')));

js = jsonencode(data,'PrettyPrint',true);
fid = fopen(fullfile(docs,'report_data.js'),'w');
fprintf(fid,'/* Auto-generated by fp_export_web.m -- do not edit */\n');
fprintf(fid,'window.PENDULUM_REPORT_DATA = %s;\n', js);
fclose(fid);

if isfile('report.html')
    copyfile('report.html', fullfile(docs,'index.html'));
end

% ---- Report -------------------------------------------------------------
sz = folder_mb(docs);
fprintf('\n  PNGs copied:   %d\n', n_png);
fprintf('  GIFs shrunk:   %d\n', n_gif);
fprintf('  Bundle size:   %.1f MB\n', sz);
if sz > o.max_mb
    fprintf(['\n  WARNING: bundle is %.1f MB, above the %g MB target.\n' ...
             '  Reduce with fewer ''gifs'', a smaller ''gif_width'',\n' ...
             '  or fewer ''disturb'' types.\n'], sz, o.max_mb);
end
fprintf('\n  Commit docs/ and enable GitHub Pages on that folder.\n\n');
end


% =========================================================================
%  PER-CONTROLLER ASSET HANDLING
% =========================================================================
function [c, n_png, n_gif] = process_ctrl(c, prefix, gif_keys, a_fig, a_ani, o)
n_png = 0; n_gif = 0;
if ~isfield(c,'assets'), return; end
a = c.assets;

pngs = {'response_png','phase_png','lyapunov_png','gains_png'};
for i = 1:numel(pngs)
    f = pngs{i};
    if isfield(a,f) && ~isempty(a.(f))
        a.(f) = copy_png(a.(f), a_fig, prefix);
        n_png = n_png + 1;
    end
end

want_gif = any(strcmp(c.key, gif_keys));
gifs = {'pendulum_gif','graphs_gif'};
for i = 1:numel(gifs)
    f = gifs{i};
    if ~isfield(a,f) || isempty(a.(f)), continue; end
    if want_gif
        outp = shrink_gif(a.(f), a_ani, prefix, o);
        a.(f) = outp;
        if ~isempty(outp), n_gif = n_gif + 1; end
    else
        a.(f) = '';
    end
end

c.assets = a;
end


function c = blank_assets(c)
if ~isfield(c,'assets'), return; end
f = fieldnames(c.assets);
for i = 1:numel(f), c.assets.(f{i}) = ''; end
end


% =========================================================================
%  COPY A PNG
% =========================================================================
function webpath = copy_png(src, a_fig, prefix)
if nargin < 3, prefix = ''; end
webpath = '';
if isempty(src) || ~isfile(src), return; end
[~,nm,ext] = fileparts(src);
dest_name  = [prefix nm ext];
copyfile(src, fullfile(a_fig, dest_name));
webpath = ['assets/figures/' dest_name];
end


% =========================================================================
%  SHRINK A GIF
% =========================================================================
function webpath = shrink_gif(src, a_ani, prefix, o)
% Re-encodes a GIF at web size: keeps every Nth frame and scales down.
% Avoids re-running the simulation — reads the existing animation directly.
webpath = '';
if isempty(src) || ~isfile(src), return; end

try
    [~,nm,~]  = fileparts(src);
    dest_name = [prefix nm '.gif'];
    dest      = fullfile(a_ani, dest_name);

    % Fast path: animate_pendulum may already have written a web-sized copy
    % during rendering (opts.web_gif). If so, just take it.
    pre = fullfile('docs','assets','anim',[nm '.gif']);
    if isfile(pre) && ~strcmp(pre, dest)
        copyfile(pre, dest);
        webpath = ['assets/anim/' dest_name];
        return;
    elseif isfile(dest)
        webpath = ['assets/anim/' dest_name];
        return;
    end

    % Slow path: shrink an existing full-size GIF.
    % Read EVERY frame in one call -- imread(...,'frames',k) in a loop
    % reopens and seeks the file each time, which is O(n^2) and painfully
    % slow on a 250-frame animation.
    [Xall, map] = imread(src, 'frames', 'all');
    nf   = size(Xall, 4);
    step = max(1, floor(nf / o.gif_frames));
    keep = 1:step:nf;

    scale = o.gif_width / size(Xall,2);
    if scale >= 1, scale = 1; end

    for k = 1:numel(keep)
        rgb = ind2rgb(Xall(:,:,1,keep(k)), map);
        if scale < 1, rgb = imresize(rgb, scale); end
        [Xs, ms] = rgb2ind(rgb, 128, 'nodither');
        if k == 1
            imwrite(Xs, ms, dest, 'gif', 'Loopcount', inf, 'DelayTime', 0.1);
        else
            imwrite(Xs, ms, dest, 'gif', 'WriteMode','append', 'DelayTime', 0.1);
        end
    end
    webpath = ['assets/anim/' dest_name];
catch ME
    fprintf('    (gif skipped: %s — %s)\n', src, ME.message);
end
end


% =========================================================================
%  HELPERS
% =========================================================================
function keys = auto_pick_gifs(ctrls)
% LQR plus the fastest-settling fuzzy controller: the pair that makes the
% central comparison of the project without shipping fourteen animations.
%
% Note: NaN metrics become null in JSON and [] after jsondecode, so every
% numeric field is read through sc() rather than used directly.
keys = {};
best = ''; bt = inf;
for i = 1:numel(ctrls)
    c = ctrls{i};
    if strcmp(c.key,'LQR'), keys{end+1} = 'LQR'; end %#ok
    ts  = sc(c,'t_settle', inf);
    cap = logical(sc(c,'captured', 0));
    if ~isempty(strfind(c.key,'Fuzzy')) && cap && isfinite(ts) && ts < bt
        bt = ts; best = c.key;
    end
end
if ~isempty(best), keys{end+1} = best; end
if isempty(keys) && ~isempty(ctrls), keys = {ctrls{1}.key}; end
end


function v = sc(s, f, default)
% Scalar field read that survives the JSON round-trip.
% jsonencode writes NaN as null; jsondecode returns [] for null.
v = default;
if ~isstruct(s) || ~isfield(s,f), return; end
x = s.(f);
if isempty(x), return; end
if ~isscalar(x), x = x(1); end
if isnumeric(x) || islogical(x), v = double(x); end
end


function o = parse_opts(args)
o = struct('run','', 'gifs',{{}}, 'gif_width',480, 'gif_frames',60, ...
           'disturb',{{'kick'}}, 'max_mb',25);
if ~isempty(args) && ischar(args{1}) && ...
   ~isempty(strfind(args{1},'Pendulum_Control_Run'))
    o.run = args{1};
    args  = args(2:end);
end
for i = 1:2:numel(args)-1
    k = lower(args{i});
    if isfield(o,k), o.(k) = args{i+1}; end
end
if ischar(o.disturb), o.disturb = {o.disturb}; end
if ischar(o.gifs),    o.gifs    = {o.gifs};    end
end


function mb = folder_mb(d)
f  = dir(fullfile(d,'**','*'));
f  = f(~[f.isdir]);
mb = sum([f.bytes]) / 1e6;
end
