% OPT_APPLY
% Reads opt_results.mat and writes the optimised gains back into the project.
%
% Two outputs:
%   1. optimised_config.m  — a MATLAB script that sets all gain variables;
%      run_all can include this with: run optimised_config
%   2. Console printout of each controller's optimised parameters with
%      the percentage improvement over the warm start
%
% Usage:
%   >> opt_apply                          % reads opt_results.mat
%   >> opt_apply('path/to/opt_results.mat')
%
% After running:
%   >> run_all                            % uses default (manual) gains
%                                         % set use_optimised_gains=true
%                                         % at the top of run_all to use
%                                         % the optimised gains instead

function opt_apply(results_file)

if nargin < 1 || isempty(results_file)
    results_file = 'opt_results.mat';
end

if ~isfile(results_file)
    error('opt_apply: %s not found. Run opt_run first.', results_file);
end

S   = load(results_file,'opt_results');
res = S.opt_results;
ctrls = fieldnames(res.controllers);

fprintf('\n');
fprintf('##########################################################\n');
fprintf('##   opt_apply — Writing Optimised Gains               ##\n');
fprintf('##########################################################\n\n');
fprintf('  Preset:   %s\n', res.preset);
fprintf('  Swing-up: %s\n', res.swingup);
fprintf('  Generated: %s\n\n', res.generated);

% =========================================================================
%  PRINT PARAMETER COMPARISON TABLE
% =========================================================================
for ci = 1:numel(ctrls)
    ctrl = ctrls{ci};
    r    = res.controllers.(ctrl);
    m    = r.best_metrics;

    fprintf('--- %s ---\n', ctrl);
    fprintf('  Cost:  warm=%.3f  ->  optimised=%.3f', ...
            nan, r.best_cost);
    fprintf('\n');

    pnames = r.param_names;
    p_opt  = r.best_params;
    p_ws   = r.warm_start;
    lb     = r.lb;
    ub     = r.ub;

    fprintf('  %-16s  %10s  %10s  %10s  %8s\n', ...
            'Parameter','WarmStart','Optimised','Bounds','Change');
    fprintf('  %-16s  %10s  %10s  %10s  %8s\n', ...
            repmat('-',1,16),repmat('-',1,10),repmat('-',1,10), ...
            repmat('-',1,10),repmat('-',1,8));

    for pi = 1:numel(p_opt)
        pname   = pnames{pi};
        v_opt   = p_opt(pi);
        v_ws    = p_ws(pi);
        bounds  = sprintf('[%.2g,%.2g]', lb(pi), ub(pi));
        if abs(v_ws) > 1e-9
            pct = (v_opt - v_ws)/abs(v_ws)*100;
            chg = sprintf('%+.0f%%', pct);
        else
            chg = '—';
        end
        fprintf('  %-16s  %10.4f  %10.4f  %10s  %8s\n', ...
                pname, v_ws, v_opt, bounds, chg);
    end

    fprintf('  Metrics: ');
    if isfield(m,'t_settle') && isfinite(m.t_settle)
        fprintf('settle=%.2fs  ', m.t_settle);
    end
    if isfield(m,'overshoot_deg') && isfinite(m.overshoot_deg)
        fprintf('overshoot=%.1fdeg  ', m.overshoot_deg);
    end
    if isfield(m,'xc_rms') && isfinite(m.xc_rms)
        fprintf('xc_rms=%.3fm  ', m.xc_rms);
    end
    if isfield(m,'total_effort') && isfinite(m.total_effort)
        fprintf('effort=%.1fN*s', m.total_effort);
    end
    fprintf('\n\n');
end

% =========================================================================
%  WRITE optimised_config.m
% =========================================================================
out_file = 'optimised_config.m';
fid = fopen(out_file,'w');

fprintf(fid,'%% OPTIMISED_CONFIG\n');
fprintf(fid,'%% Auto-generated by opt_apply on %s\n', ...
        char(datetime('now','Format','yyyy-MM-dd HH:mm:ss')));
fprintf(fid,'%% Preset: %s  |  Swing-up: %s\n', res.preset, res.swingup);
fprintf(fid,'%% Cost weights: [%.1f %.1f %.1f %.1f]\n', res.cost_weights);
fprintf(fid,'%%\n');
fprintf(fid,'%% Include in run_all by setting:\n');
fprintf(fid,'%%   use_optimised_gains = true;\n');
fprintf(fid,'%% at the top of the CONFIG block.\n');
fprintf(fid,'%%\n');
fprintf(fid,'%% DO NOT EDIT — regenerate with opt_apply.\n\n');

% ---- LQR ---------------------------------------------------------------
% params = [Q1 Q2 Q3 Q4 qi R]
if isfield(res.controllers,'LQR')
    p = res.controllers.LQR.best_params;
    fprintf(fid,'%% --- LQR ---\n');
    fprintf(fid,'lqr_Q  = [%.6g  %.6g  %.6g  %.6g];\n', p(1),p(2),p(3),p(4));
    fprintf(fid,'lqr_qi = %.6g;\n', p(5));
    fprintf(fid,'lqr_R  = %.6g;\n\n', p(6));
end

% ---- Classical PID -----------------------------------------------------
% params = [kp kd ki kp_gov kd_gov max_tilt]
if isfield(res.controllers,'ClassicalPID')
    p = res.controllers.ClassicalPID.best_params;
    fprintf(fid,'%% --- ClassicalPID ---\n');
    fprintf(fid,'pid_kp = %.6g;\n', p(1));
    fprintf(fid,'pid_kd = %.6g;\n', p(2));
    fprintf(fid,'pid_ki = %.6g;\n', p(3));
    fprintf(fid,'govcfg_ClassicalPID = struct(''kp_gov'',%.6g,''kd_gov'',%.6g,''max_tilt'',%.6g);\n\n', ...
            p(4), p(5), p(6));
end

% ---- Fuzzy PID variants -------------------------------------------------
% params = [kp_max kd_max inner_scale kp_gov kd_gov max_tilt]
fz = {'FuzzyPID_Sugeno','FuzzyPID_Mamdani','FuzzyPID_Type2'};
for fi = 1:numel(fz)
    fname = fz{fi};
    if ~isfield(res.controllers, fname), continue; end
    p = res.controllers.(fname).best_params;
    fprintf(fid,'%% --- %s ---\n', fname);
    fprintf(fid,'%s_kp_max = %.6g;\n', fname, p(1));
    fprintf(fid,'%s_kd_max = %.6g;\n', fname, p(2));
    fprintf(fid,'govcfg_%s = struct(''kp_gov'',%.6g,''kd_gov'',%.6g,''max_tilt'',%.6g,''inner_scale'',%.6g);\n\n', ...
            fname, p(4), p(5), p(6), p(3));
end

% ---- Adaptive fuzzy -----------------------------------------------------
% params = [kp_max kd_max eta_kp eta_kd kp_gov kd_gov]
if isfield(res.controllers,'AdaptiveFuzzy')
    p = res.controllers.AdaptiveFuzzy.best_params;
    fprintf(fid,'%% --- AdaptiveFuzzy ---\n');
    fprintf(fid,'adapt_kp_max = %.6g;\n', p(1));
    fprintf(fid,'adapt_kd_max = %.6g;\n', p(2));
    fprintf(fid,'adapt_eta_kp = %.6g;\n', p(3));
    fprintf(fid,'adapt_eta_kd = %.6g;\n', p(4));
    fprintf(fid,'govcfg_AdaptiveFuzzy = struct(''kp_gov'',%.6g,''kd_gov'',%.6g);\n\n', ...
            p(5), p(6));
end

% ---- Fuzzy SMC ----------------------------------------------------------
% params = [lambda phi_b K_min K_max kp_gov kd_gov]
if isfield(res.controllers,'FuzzySMC')
    p = res.controllers.FuzzySMC.best_params;
    fprintf(fid,'%% --- FuzzySMC ---\n');
    fprintf(fid,'smc_lambda       = %.6g;\n', p(1));
    fprintf(fid,'smc_phi_boundary = %.6g;\n', p(2));
    fprintf(fid,'smc_K_min        = %.6g;\n', p(3));
    fprintf(fid,'smc_K_max        = %.6g;\n', p(4));
    fprintf(fid,'govcfg_FuzzySMC = struct(''kp_gov'',%.6g,''kd_gov'',%.6g);\n\n', ...
            p(5), p(6));
end

fprintf(fid,'%% The govcfg_<Controller> structs above hold per-controller governor\n');
fprintf(fid,'%% gains. run_all applies one govcfg for the whole run, so assign the\n');
fprintf(fid,'%% one you want, e.g.:   govcfg = govcfg_FuzzyPID_Sugeno;\n\n');

fclose(fid);
fprintf('[opt_apply] Written: %s\n\n', out_file);

% =========================================================================
%  PATCH run_all.m
% =========================================================================
% Add/update the use_optimised_gains toggle and include block at the top
% of the CONFIG section in run_all.m, if it doesn't already exist.
patch_run_all(res);

fprintf('NEXT STEPS:\n');
fprintf('  1. Open run_all.m\n');
fprintf('  2. Set  use_optimised_gains = true;  at the top of CONFIG\n');
fprintf('  3. Run  >> run_all\n\n');

end  % function opt_apply


% =========================================================================
%  PATCH run_all.m
% =========================================================================
function patch_run_all(res)
run_all_file = 'run_all.m';
if ~isfile(run_all_file)
    fprintf('[opt_apply] run_all.m not found — skipping patch.\n');
    return;
end

src = fileread(run_all_file);

% Check if toggle already exists
if contains(src, 'use_optimised_gains')
    fprintf('[opt_apply] run_all.m already has use_optimised_gains toggle.\n');
    return;
end

% Find the CONFIG block marker and insert the toggle + loader after it
insert_marker = '% =========================================================================';
config_marker = '%  CONFIGURATION';
idx = strfind(src, config_marker);
if isempty(idx)
    fprintf('[opt_apply] Could not find CONFIG block in run_all.m — skipping patch.\n');
    return;
end

% Find the next newline after the closing === line after the config marker
eom = idx(1);
% Move forward to end of that marker block (next blank line)
next_nl = eom + find(src(eom:end) == newline, 3);
if numel(next_nl) < 3
    fprintf('[opt_apply] Could not locate insertion point — skipping patch.\n');
    return;
end
ins_pos = next_nl(3);  % insert after third newline past config header

toggle_block = sprintf([...
    '\n%% ---- Optimised gains toggle ----------------------------------------\n'...
    '%% Set to true to use gains from opt_run / optimised_config.m\n'...
    'use_optimised_gains = false;\n'...
    'if use_optimised_gains && isfile(''optimised_config.m'')\n'...
    '    run optimised_config;\n'...
    '    fprintf(''[run_all] Using OPTIMISED gains from optimised_config.m\\n'');\n'...
    'end\n'...
    '%% -------------------------------------------------------------------\n\n']);

new_src = [src(1:ins_pos-1), toggle_block, src(ins_pos:end)];

fid = fopen(run_all_file,'w');
fwrite(fid, new_src, 'char');
fclose(fid);
fprintf('[opt_apply] Patched run_all.m with use_optimised_gains toggle.\n');
end
